apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-cars
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-cars
    spec:
      containers:
        - name: cars-pod
          image: dacdo/cars:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: car-svc
  labels:
    app: api-cars
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: api-cars

