apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-cars
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-cars
    spec:
      containers:
        - name: cars-pod
          image: dacdo/cars:latest
          ports:
            - containerPort: 8080
