apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-pod
          image: dacdo/eureka:latest
          ports:
            - containerPort: 8761
